services:
  scraper-0:
    build: .
    environment:
      - SCRAPE_OFFSET=0
    volumes:
      - ./data:/app/data
      - ./notify/envs:/app/notify/envs:ro
    entrypoint: ["/app/notify/docker_entrypoint.sh"]
    restart: unless-stopped

  scraper-20:
    build: .
    environment:
      - SCRAPE_OFFSET=20
    volumes:
      - ./data:/app/data
      - ./notify/envs:/app/notify/envs:ro
    entrypoint: ["/app/notify/docker_entrypoint.sh"]
    restart: unless-stopped

  scraper-40:
    build: .
    environment:
      - SCRAPE_OFFSET=40
    volumes:
      - ./data:/app/data
      - ./notify/envs:/app/notify/envs:ro
    entrypoint: ["/app/notify/docker_entrypoint.sh"]
    restart: unless-stopped

  scraper-60:
    build: .
    environment:
      - SCRAPE_OFFSET=60
    volumes:
      - ./data:/app/data
      - ./notify/envs:/app/notify/envs:ro
    entrypoint: ["/app/notify/docker_entrypoint.sh"]
    restart: unless-stopped

  scraper-80:
    build: .
    environment:
      - SCRAPE_OFFSET=80
    volumes:
      - ./data:/app/data
      - ./notify/envs:/app/notify/envs:ro
    entrypoint: ["/app/notify/docker_entrypoint.sh"]
    restart: unless-stopped

  scraper-100:
    build: .
    environment:
      - SCRAPE_OFFSET=100
    volumes:
      - ./data:/app/data
      - ./notify/envs:/app/notify/envs:ro
    entrypoint: ["/app/notify/docker_entrypoint.sh"]
    restart: unless-stopped
